
import CGData
import CGData.BaseMatrix

from copy import copy

def sortedSamples(samples):
    import os, re
    # Check for numeric sample ids. Allow for a common prefix
    # before the number.
    prefix = os.path.commonprefix(samples)
    plen = len(prefix)
    if reduce(lambda x,y: x and y, map(lambda s: re.match('^' + prefix + '[0-9]+$', s), samples)):
        return sorted(samples, cmp=lambda x, y: int(x[plen:]) - int(y[plen:]))
    else:
        return sorted(samples)

class ClinicalMatrix(CGData.BaseMatrix.BaseMatrix):
    
    __format__ = {
        "name" : "clinicalMatrix",
        "type" : "type",
        "form" : "matrix",
        "rowType" : "idMap",
        "colType" : "clinicalFeature",
        "valueType" : "str",
        "nullString" : ""
    }


    def __init__(self):
        super(ClinicalMatrix, self).__init__()

    def init_blank(self, cols, rows):
        super(ClinicalMatrix, self).init_blank(cols=cols,rows=rows,skip_numpy=True)
        if 'cgdata' not in self:
            self['cgdata'] = { 'type' : 'clinicalMatrix' }

    def __guess_type__(self, values):
        type = 'float'
        for value in values:
            try:
                a = float(value)
            except ValueError:
                type = 'category'
                break
        return type
    
    def expand(self, iddag):
        if not self.loaded:
            self.load()
        rows = {}
        #get the rows that part of the original matrix
        for r in self.get_row_list():
            rows[r] = None
        #get the rows that will be generated by the copy info from a ancestor
        for r in self.get_row_list():        
            for d in iddag.get_descendants(r):
                if d not in rows:
                    rows[d] = r #later will turn this into list of all acestors
        out = ClinicalMatrix()
        out.update(self)
        out.init_blank(cols=self.get_col_list(), rows=rows)
        for row in rows:
            if rows[row] is None:
                for col in self.get_col_list():
                    out.set_val(col_name=col, row_name=row, value=self.get_val(col_name=col, row_name=row))
            else:
                for col in self.get_col_list():
                    out.set_val(col_name=col, row_name=row, value=self.get_val(col_name=col, row_name=rows[row]))
        return out
    
    def merge(self, other):
        rows = {}
        #get the rows that part of the original matrix
        for r in self.get_row_list():
            rows[r] = None
        if other is not None:
            for r in other.get_row_list():
                rows[r] = None
        cols = {}
        #get the cols that part of the original matrix
        for r in self.get_col_list():
            cols[r] = None
        if other is not None:
            for r in other.get_col_list():
                cols[r] = None
        out = ClinicalMatrix()
        out.update(self)
        out.init_blank(cols=cols, rows=rows)
        for row in self.get_row_list():
            for col in self.get_col_list():
                out.set_val(col_name=col, row_name=row, value=self.get_val(col_name=col, row_name=row))
        if other is not None:
            for row in other.get_row_list():
                for col in other.get_col_list():
                    out.set_val(col_name=col, row_name=row, value=other.get_val(col_name=col, row_name=row))
        return out
    
    def transform(self, feat):
        featmap = feat.get_feature_map()
        col_types = []
        for col_name in self.get_col_list():
            if col_name in featmap:
                if 'valueType' in featmap[col_name]:
                    ftype = featmap[col_name]['valueType'][0]
                    if ftype.value == 'float':
                        col_types.append(float)
                    else:
                        col_types.append(str)
                else:
                    col_types.append(str)
            else:
                col_types.append(str)
        return TypedClinicalMatrix(col_types, self)

class TypedClinicalMatrix(ClinicalMatrix):
    def __init__(self, col_types, cmatrix):
        ClinicalMatrix.__init__(self)
        self.matrix = []
        self.col_types = col_types
        self.loaded = True

        for rowname in cmatrix.get_row_list():
            row = []
            for i, col in enumerate(cmatrix.get_row(rowname)):
                if col is not None:
                    row.append( col_types[i](col) )
                else:
                    row.append(None)
            self.matrix.append(row)
        
        self.row_map = copy(cmatrix.row_map)
        self.col_map = copy(cmatrix.col_map)
